### ISSUE TITLE
Render documentation with swagger-ui

### ISSUE THREAD

**Issue by TiMESPLiNTER** [zalando/intellij-swagger#105]
It would be great to have the swagger/openAPI file rendered on the fly using swagger-ui in a split screen view.

**Comment by semonte** [comment]
@TiMESPLiNTER That would be great indeed. If someone has knowledge already on how to do that, please contribute :) I will look for possible solutions if no one picks this up.

**Comment by semonte** [comment]
Fixed in https://github.com/zalando/intellij-swagger/pull/124

**Comment by iAbhi1995** [comment]
@semonte the code for swagger-ui is no more part of the master branch.
Cannot find the split button to render swagger-ui.
Is this feature removed?
