### ISSUE TITLE
Nothing rendered

### ISSUE THREAD

**Issue by maclonghorn** [zalando/intellij-swagger#106]
Installed the 1.0.0 release, PHPStorm 2017.2.4.
I have an existing YML file that worked with the previous release.  When I click the browser icon to view, i only get a header, nothing else, no errors, etc.

**Comment by semonte** [comment]
@maclonghorn are you 100% sure it is the exact same file? Empty Swagger UI is shown if the conversion from YAML to JSON fails.

**Comment by maclonghorn** [comment]
Yes, same file.  However, I removed a bunch of code to simplify it (about 100 lines remaining) and it worked fine.  Then I added those lines back and it's working.  Something getting cached?

**Comment by semonte** [comment]
The Swagger UI is updated every time the file is saved, this is done asynchronously. Refreshing the swagger UI immediately after a save might not display the latest version. Perhaps this was the case. 

@maclonghorn if this is causing you more issues, please get back to me.

**Comment by maclonghorn** [comment]
No, that wasn't it.  PHPStorm always saves automatically, and I refreshed several times.  Plus, if that were the case, I would at least see something, instead of just the header/search.
