### ISSUE TITLE
Issue on caching with Swagger UI

### ISSUE THREAD

**Issue by chmika** [zalando/intellij-swagger#107]
I worked on a yaml file, I used the icon to see the rendring on the browser, but I'm not getting the file I'm working on but the one i worked on before, I think it need a way to refresh the content of the file generated for the browser rendring.

Regards.

**Comment by semonte** [comment]
Thanks for the issue. The Swagger UI is rendered each the the spec file is saved, overwriting whatever existed before. Can you confirm that saving the file and reloading the browser works for you?

**Comment by chmika** [comment]
Hi, thanks for your response, 
Yes all files are saved, I have many swagger files, when I change the active file on intellij and I click on  the browser icon to desplay swager UI rendring, I have an old file on swagger UI, to bypass this behavior, each time I have to delete manually the temporary repository  ..../AppData/Local/Temp/swagger-ui1234

**Comment by Guido125** [comment]
Can confirm - having the same issue myself. I've been typing a character in the file tab that has focus as a work around.

Similar issue - changing branches through terminal isn't triggering an update either.

**Comment by semonte** [comment]
Ok I understand the issue. As a fix, I the Swagger UI will be always re-rendered when the browser icon is clicked. If working with the same file, the UI is rendered on the fly when the spec file is saved.

Do you have other ideas or suggestions?

**Comment by semonte** [comment]
@Guido125 @melamm can you verify that the fix works for your use cases by installing the attached version manually?
[intellij-swagger.zip](https://github.com/zalando/intellij-swagger/files/1401000/intellij-swagger.zip)

**Comment by stessy** [comment]
Hi,

I had the same issue.
I just installed the version you provided and the problem seems to be solved.
When I edit a yaml the changes are reflected when I preview it in the browser.
When I switch to another yaml and I preview it, the new one is correctly displayed in the browser.

Thanks for the quick fix.
Kind regards.

**Comment by chmika** [comment]
Hi;
Yes the issue is fixed with the new version, thanks @semonte 

Regards

**Comment by semonte** [comment]
Great, I will publish the new version next week in the JetBrains plugins repository. Thanks for the help!
