### ISSUE TITLE
Swagger UI not OAS 3.0 Capable

### ISSUE THREAD

**Issue by Guido125** [zalando/intellij-swagger#108]
I used [this](https://raw.githubusercontent.com/OAI/OpenAPI-Specification/OpenAPI.next/examples/v3.0/petstore.yaml) to generate a page using swagger UI. However, there are a number of things missing when comparing it to the generated page from editor.swagger.io - the main one being all endpoint responses.

I think the cause is due to the version of Swagger UI used. The first Swagger UI release to support OAS 3.0 was [Swagger UI 3.1.0](https://github.com/swagger-api/swagger-ui/releases/tag/v3.1.0), yet this plugin looks like it's using 3.0.18.

A version bump to latest stable version should solve the issue.

**Comment by semonte** [comment]
Thanks for the issue. The Swagger UI indeed should be updated to the newest version. @Guido125 would like to make a PR :) ?

**Comment by Guido125** [comment]
Never done any plugin development before - just Android (Android Studio is IntelliJ based). I did a quick search, but I didn't find an easy way to get started. What links would you recommend?

**Comment by semonte** [comment]
I started by reading https://www.jetbrains.org/intellij/sdk/docs/welcome.html and testing things out. Looking at different plugin and intellij source code is also helpful. Let me know if you need any help!

**Comment by semonte** [comment]
Fixed in https://github.com/zalando/intellij-swagger/pull/117/commits/fc1625989d1849af34578af912147dd1ace5c4e0

**Comment by ynodir** [comment]
@semonte when's the next release with this issue fixed?

**Comment by semonte** [comment]
@ynodir I will aim to release this week.
