### ISSUE TITLE
Problem with markdown in description

### ISSUE THREAD

**Issue by Frevant** [zalando/intellij-swagger#111]
Not really important, but ...

When using markdown in a description field, it is ignored when rendered:

_online editor result:_
![2017-10-24 11_51_07-swagger editor - internet explorer](https://user-images.githubusercontent.com/29484427/31936445-dfcf01d8-b8b1-11e7-9a7b-c37434182baf.png)

_plugin result:_
![2017-10-24 11_50_40-swagger ui](https://user-images.githubusercontent.com/29484427/31936454-e8483cb2-b8b1-11e7-856f-254119f95ea7.png)

Gtz,

Frederik

**Comment by semonte** [comment]
@Frevant thanks for reporting the issue. Is the spec YAML or JSON?

**Comment by semonte** [comment]
Closing the issue, I can't reproduce this with the latest version of the plugin.
