### ISSUE TITLE
Browser icons open UI in other browsers, but not Chrome

### ISSUE THREAD

**Issue by dmolesUC** [zalando/intellij-swagger#115]
For some reason the Chrome URI is

```
chrome-extension://hmhgeddbohgjknpmjagkdomcpobmllji/private/var/folders/8s/45cxv60949735s2r_5sjh5gh0000gn/T/swagger-ui/index.html
```

(which produces "Your file was not found"), while the Safari and Opera URI is

```
file:///var/folders/8s/45cxv60949735s2r_5sjh5gh0000gn/T/swagger-ui/index.html
```

Here's my system info:

```
IntelliJ IDEA 2017.2.5
Build #IU-172.4343.14, built on September 25, 2017
JRE: 1.8.0_152-release-915-b12 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6
```

**Comment by semonte** [comment]
It seems that the JetBrains IDE Support (https://chrome.google.com/webstore/detail/jetbrains-ide-support/hmhgeddbohgjknpmjagkdomcpobmllji?hl=en) Chrome extension is intercepting the file URL. I can only suggest you to use another browser when using the Swagger UI ...
