### ISSUE TITLE
Add ability to validate swagger file

### ISSUE THREAD

**Issue by xp-vit** [zalando/intellij-swagger#118]
When I paste the content of my swagger file to http://editor.swagger.io/ it reports a lot of errors(bad indentation, semantic errors, schema errors), while plugin itself doesn't report anything.

This is the request to add the ability to provide the same level of validation in the plugin. To achieve this we can go following ways:
1. Implement validations in plugin
2. Use the http://editor.swagger.io/ api to validate and show erors reported.
3. Add a shortcut which will open http://editor.swagger.io/ with the content of current swagger file already pasted.

**Comment by semonte** [comment]
@xp-vit Thanks for creating the issue. There is already some validation for Swagger files, but it is not complete. Can you post the spec file for testing purposes?

**Comment by keilw** [comment]
I changed a datatype to an incorrect "objekt" instead of "object" which the Swagger online editor flags as invalid, but the plugin currently does not.

**Comment by semonte** [comment]
@keilw Thanks for the feedback. 

Validation has not been worked on recently. Now that the Open API support is mostly done, proper validation could be next in the priority list.

**Comment by cognifloyd** [comment]
I found that specifying a JSON schema (`openapi-3.0` or `swagger-2.0`) warns about a lot of the errors that the Swagger Editor detects. Maybe this plugin can enable that by default.
https://www.jetbrains.com/help/idea/json.html#ws_json_using_schemas

**Comment by wabiloo** [comment]
I also would like some additional validation.
In particular, validating that the $ref references are pointing to valid files.
Eg. 
```paths:
    /root/inputs:
        $ref: './paths/roots/inputs.yaml'
```
If there is no such inputs.yaml file, the plugin should detect it and give a warning

**Comment by semonte** [comment]
> I found that specifying a JSON schema (openapi-3.0 or swagger-2.0) warns about a lot of the errors that the Swagger Editor detects. Maybe this plugin can enable that by default.
https://www.jetbrains.com/help/idea/json.html#ws_json_using_schemas

I have been planning to take a look at this! This would likely be a big help with keeping spec files valid.

**Comment by semonte** [comment]
> In particular, validating that the $ref references are pointing to valid files.

Agree, created an issue #226

**Comment by cognifloyd** [comment]
in #227, I was looking for libraries that could be integrated. In doing so I came across these linters.
Most of them aren't Java, and those that are implement their own parser as well, so I'm not sure how embeddable these could be. But, all of them might offer hints about how to do validation logic beyond using the json schema.

- https://github.com/networknt/openapi-parser (java parser/validator)
- https://github.com/RepreZen/KaiZen-OpenApi-Parser (java parser/validator)
- https://github.com/IBM/openapi-validator (javascript)
- https://github.com/p1c2u/openapi-spec-validator (python)
- https://github.com/APIDevTools/swagger-parser (javascript parser/validator)
- https://godoc.org/github.com/go-openapi/validate (go)
- https://github.com/wework/speccy (javascript)

**Comment by semonte** [comment]
Thanks for the list @cognifloyd I will start with a JSON Schema validation as a "low hanging fruit", and iterate on top of that.

**Comment by semonte** [comment]
A Swagger/OpenAPI specification file is currently validated with a JSON Schema. On top of that, we validate that references point to existing objects. 

I will close this issue; validation issues should be handled by individual issues from now on.
