### ISSUE TITLE
Reparses on changes in unrelated files.

### ISSUE THREAD

**Issue by ettavolt** [zalando/intellij-swagger#126]
This greatly slows down IDEA's inspections.
To reproduce:
1. Open a large Swagger file (mine is ~10k lines).
1. In a 'split view' open some other file (like simple text one). You should have both Swagger and 'trigger' file visible.
1. Wait for initial parse to finish (you'll see inspections indicator above scrollbar as some icon but an eye).
1. Edit the other file.
1. Observe eye indicator for both files.

With my Swagger file, inspections don't yield any result for ~1.5 minute.

**Comment by semonte** [comment]
Thanks for reporting the issue, I have verified that the inspections do take a long time with a big file.

> Reparses on changes in unrelated files.

I also tested this with other file types. The analysis is triggered in a split view regardless of the file type, so this behaviour is not intellij-swagger plugin related.

Is the slow analysis causing you issues? Sure it should be faster, but I would like to prioritize this first.

**Comment by ettavolt** [comment]
[Filed issue for JetBrains.](https://youtrack.jetbrains.com/issue/IDEA-184358)
I forgot to add here that edited file is not highlighted until inspections in all views are run. Not sure if JetBrains finds a way to break the bonds, so speeding up analysis may be the only solution.
Is it possible to analyze kind of 'incrementally', of what has changed?

**Comment by semonte** [comment]
> Is it possible to analyze kind of 'incrementally', of what has changed?

I don't think so. I will investigate if there are some clear reasons why the inspections are slow. Keeping this open for now.

**Comment by semonte** [comment]
Closing this, not much I can do about this.
