### ISSUE TITLE
Embedded Swagger UI encoding issue

### ISSUE THREAD

**Issue by semonte** [zalando/intellij-swagger#127]
See screenshot:

![image](https://user-images.githubusercontent.com/1151536/34479000-68eeca24-efa4-11e7-8c24-a2b291cf7667.png)

**Comment by semonte** [comment]
@irishshagua Do you have an idea what could be the issue?

**Comment by semonte** [comment]
Might be related to https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8175802

**Comment by irishshagua** [comment]
Haven't seen that. @semonte do you have some steps to reproduce? I'm using a mac and was building locally with java 1.8.0_151 and cannot reproduce... :-/

**Comment by semonte** [comment]
I just open a Swagger file. I have also a Mac with java 1.8.0_151. 

Here is the zip file:

[intellij-swagger.zip](https://github.com/zalando/intellij-swagger/files/1597364/intellij-swagger.zip)

**Comment by irishshagua** [comment]
I'll try and have a look tonight...

**Comment by irishshagua** [comment]
I tried to reproduce this again on 2 seperate setups (mac and linux) but no joy... :-/
I'm kinda stumped as to how to even start investigating. According to the linked bug this should be fixed in 8u152:
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8088205

🤷‍♂️

**Comment by semonte** [comment]
Ok, that is weird indeed. I will try to fix this by changing the font to something that is installed as default in OS.

**Comment by semonte** [comment]
@irishshagua I fixed the font issue by removing the Google fonts from Swagger UI. The fonts did not work on my setup and probably other users would have experienced the same issue. 

I will publish a new version of the plugin next week to get this out in the open!

**Comment by semonte** [comment]
Fixed in https://github.com/zalando/intellij-swagger/commit/5ebba5bf63cf3e76d0deab683e755aa9f502d724

**Comment by nandotorterolo** [comment]
<img width="381" alt="screen shot 2018-07-03 at 5 45 44 pm" src="https://user-images.githubusercontent.com/8540107/42243816-f3586fca-7ee8-11e8-8bf2-7febc9613db2.png">

IDE: `2018.1`
Plugin: `0.12.0`

**Comment by nandotorterolo** [comment]
@semonte  do you know how to avoid this encoding issue?

**Comment by semonte** [comment]
The embedded UI was removed due to multiple issues reported by users. You should update the plugin to the latest version.
