### ISSUE TITLE
Splitting editor window hangs UI

### ISSUE THREAD

**Issue by ericraymond** [zalando/intellij-swagger#128]
With the latest versions of plugin and Idea, if you split a swagger window (vertically or horizontally), the IDE hangs with a spinning rainbow mouse cursor (at least on OSX High Sierra).  Hangs entire IDE (including other projects that are open).

Notet that the split window has a top row with three icons: 
![image](https://user-images.githubusercontent.com/22483767/35007734-5cdca0ba-faaf-11e7-94db-b89ed1ff22be.png)

**Comment by semonte** [comment]
Thanks for reporting an issue.

Are you able to provide an example Swagger spec so that I could reproduce the issue?

**Comment by semonte** [comment]
Split view has been disabled for now.
