### ISSUE TITLE
Swagger UI preview does not work under windows

### ISSUE THREAD

**Issue by hilmarv** [zalando/intellij-swagger#129]
Tested on Windows 10 with WebStorm and Rider. The Swagger UI only shows a white canvas. The context menu has only one entry: Reload page. But that leaves you with the same white canvas.

**Comment by robtha** [comment]
I have the problem running the plugin with intellij idea 2017.3 under windows 10.
No swagger ui shown, no error message.

**Comment by bartroodzant** [comment]
I have the same issue running PHPStorm 2017.2.2 and after I updated to PHPStorm 2017.3.3 on Windows 10.

**Comment by semonte** [comment]
Thanks for reporting an issue.

Are you facing the issue with the embedded Swagger UI inside the IDEA or in the Swagger UI that is shown in the browser by clicking a browser icon at the top right corner? Or both?

**Comment by robtha** [comment]
for me, the problem only occures with the embedded swagger ui inside IDEA

**Comment by semonte** [comment]
@irishshagua Would you have time to look at this issue? This probably has something to do with how file paths are different in OS X vs Windows.

**Comment by irishshagua** [comment]
Will do. Just need to find a windows machine to play with... :)
Are there any logs or errors in the event log when this happens?

**Comment by esiha** [comment]
@irishshagua No errors or logs whatsoever in the event log :(

**Comment by semonte** [comment]
@irishshagua I was able to reproduce the issue with virtual machine https://developer.microsoft.com/en-us/windows/downloads/virtual-machines

**Comment by Frevant** [comment]
Just for information:
Have same issue with Intellij 2017.3.1, running on windows 7 enterprise Service Pack 1, swagger plugin version 1.0.4
Only with embedded version. Clicking and opening in external browsers (IE and Chrome) works fine.

**Comment by irishshagua** [comment]
Apologies for the delay. Had a go-live this week so was up to me tits... :)
Fix for the issue is here. Silly mistake on the paths.... my bad....

https://github.com/zalando/intellij-swagger/pull/132

**Comment by semonte** [comment]
Fixed in https://github.com/zalando/intellij-swagger/pull/132
