### ISSUE TITLE
Completion for standard swagger types 

### ISSUE THREAD

**Issue by viatra2** [zalando/intellij-swagger#13]
OAI spec supports the following types: 
- standard json-schema types 
- additional 'file' types (in some places, not everywhere)
- additional 'format' property, as described at https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types

I would expect that plugin simplifies entering / editing the types 
- As a first step (covered by this issue), just basic completion of the exact `type` and `format` values shall be implemented. 
- Some additional logic for type vs format compatibility may be added, e.g if the type "number" is already set, then format "int32" should probably NOT be suggested, since it is only valid for "integer" type

**Comment by semonte** [comment]
@viatra2 Do you want to work on this?

**Comment by viatra2** [comment]
@semonte Yes, this time I am going to add real code, not just tests :). 
Not sure about exact ETA, but should have some time this week.

**Comment by semonte** [comment]
Commit 36c757847f990e4b455aa2339e9838ca4aaa127e adds type value auto completion.
