### ISSUE TITLE
Cursor keeps disappearing

### ISSUE THREAD

**Issue by shayded-exe** [zalando/intellij-swagger#130]
When I open a swagger file or switch between tabs in split view via keyboard shortcut, the cursor disappears and I have to click inside the file to get it back.

I didn't used to have this issue before the release that added the little toolbar at the top of swagger files.
I rely almost entirely on keyboard shortcuts so this issue pretty much means I have to disable the plugin for now.

If the overlay toolbar is in fact causing the issue, maybe you could provide an option to disable it as a temporary workaround? Either way it would still actually be nice to disable it anyways.

WebStorm 2017.3.3
Build #WS-173.4301.22, built on January 15, 2018
JRE: 1.8.0_151-b12 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
Windows 7 6.1

**Comment by semonte** [comment]
@PachowStudios Thanks for reporting an issue. I don't know what is causing the issue at the moment, but as a workaround you can download the previous version 1.0.3 from https://plugins.jetbrains.com/plugin/8347-swagger-plugin?

I was able to reproduce the issue, so it's a start :)

**Comment by semonte** [comment]
@PachowStudios are you still experiencing the issue with the latest version 1.0.7?

**Comment by shayded-exe** [comment]
The new text-only editor works great just like it used to on 1.0.7!

The Swagger UI editor still has the issue of course, but that's fine by me considering that I can't even use it because I have a lot of linked yaml files, which the editor doesn't support. I might open a separate issue for that and dig through the code to see if I can get it working.

**Comment by semonte** [comment]
Great! I will close this issue then.
