### ISSUE TITLE
Plugin not detecting openapi3 yaml file

### ISSUE THREAD

**Issue by hskrasek** [zalando/intellij-swagger#131]
Just installed the plugin and started working on an OpenAPI 3 spec file, but none of the auto complete or Swagger-UI options are showing up. I've seen that OpenAPI 3 support was added and supported, so not sure whats wrong. 

PhpStorm 2017.3.3
Build #PS-173.4301.34, built on January 18, 2018
JRE: 1.8.0_152-release-1024-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.2

**Comment by semonte** [comment]
Thanks for reporting an issue. Do you have an example file or a screenshot? I am not able to reproduce the issue.

**Comment by hskrasek** [comment]
Here an example file in YAML format:

```yaml
openapi: 3.0.0
servers:
  - url: 'https://api.conferences.com'
info:
  description: >-
    The conference API allows public users to get a list of talks,
    tutorials and attendees.
  version: 1.0.0
  title: Conference API
  contact:
    name: Hunter Skrasek
    url: 'https://twitter.com/hskrasek'
tags:
  - name: attendees
    description: Find out who is attending a conference
paths:
  /attendees:
    post:
      tags:
        - attendees
      operationId: create-attendee
      summary: Add a new attendee to the conference
      requestBody:
        description: Pet to add to the store
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewAttendee'
      responses:
        '201':
          description: Successfully added an attendee to the conference
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AttendeeResponse'
components:
  schemas:
    NewAttendee:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
      required:
        - first_name
        - last_name
    AttendeeResponse:
      type: object
      properties:
        data:
          type: object

```

**Comment by junpayment** [comment]
@hskrasek
I think it's due to the previous version of swagger-ui and swagger-editor did not support OAP version 3.
They support that now, so I think it will work now.

https://swagger.io/blog/support-for-oas-3-0-in-swagger-editor-and-swagger-ui/

**Comment by semonte** [comment]
I tested this with PhpStorm with the given sample, I can't reproduce the issue. @hskrasek are you still experiencing this with the latest version of the plugin (1.0.7)?

**Comment by hskrasek** [comment]
@semonte I'm actually on 1.0.5, can't seem to see the 1.0.7 update yet. But my bad everyone, the plugin is now working. Only thing I noticed is that I have to create the file first with `openapi: 3.0.0`, close the file and then re-open it for the IDE to recognize it. But that might just be a 1.0.5 thing

**Comment by semonte** [comment]
Ok, glad to hear that!
