### ISSUE TITLE
Going into $ref not working

### ISSUE THREAD

**Issue by jnazander** [zalando/intellij-swagger#134]
Going into `$ref` by ctrl+clicking on the reference doesn't seem to work in most cases - it only works when it's either a reference to another file, or when it's in the format "#/definitions/[somekey]"

If I just have a local reference that doesn't have the string "definitions" in it, it fails to go to it.

Simplest example:

![image](https://user-images.githubusercontent.com/4726607/35620301-711ac3d2-0689-11e8-958c-88b74ba78d1b.png)
it cannot find `bar` even through it's right on the very next line!

Some more cases:
![image](https://user-images.githubusercontent.com/4726607/35620989-8c66b14e-068b-11e8-8479-1926ef20d66b.png)

**Comment by semonte** [comment]
Thanks for reporting an issue. The examples are not valid in Swagger specification, so the references do not work. For example, `paths` can't have a child named `$ref`.

**Comment by jnazander** [comment]
@semonte the first picture is a valid Swagger specification. Swagger supports linking external files, using $ref, right? And these external files can be in free form (if, for example, I extract one model definition into a separate `definition.yaml`, then the contents of it can be any node hierarchy I want)

**Comment by semonte** [comment]
Can you paste a code example of what should work? The `$ref` key can't be placed in all places, for example under the `paths` key.

**Comment by jnazander** [comment]
My first screenshot is a perfectly valid example of what should work. Suppose that it's a file called MyDefinition.yaml and it's referenced somewhere in the main `swagger.yaml` file like this:

`$ref: "MyDefinition.yaml#/foo"`

**Comment by semonte** [comment]
Ok got it, that needs to be fixed indeed!
