### ISSUE TITLE
Structure ist no longer available window is emtpy ("No structure")

### ISSUE THREAD

**Issue by thorstenspringhart** [zalando/intellij-swagger#139]
I am using the plugin with Rubymine. Since the last update of the plugin, the structure of the swagger.yaml is not longer available, only "No structure" is shown
The structure window is very helpful to navigate in big swagger files...

**Comment by pvince** [comment]
I have seen the same thing using:
> IntelliJ IDEA 2017.3.4 (Ultimate Edition)
> Build #IU-173.4548.28, built on January 29, 2018
> JRE: 1.8.0_152-release-1024-b11 amd64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Windows 10 10.0

I have also noticed that restarting IntelliJ resolves the issue temporarily. I have not noticed a particular action that causes the 'Structure' to revert to 'No Structure', other than at some point during the day I will switch back to the 'Structure' tab and it will not be populated.

**Comment by semonte** [comment]
Thanks for reporting an issue.  The new version 1.0.7 at https://plugins.jetbrains.com/plugin/8347-swagger-plugin will fix the structure view, it is pending for an approval.
