### ISSUE TITLE
AWS API Gateway Swagger type support

### ISSUE THREAD

**Issue by MaxVynohradov** [zalando/intellij-swagger#141]
It's rely cool if intellij-swagger will be support AWS API Gateway features, such as  _x-amazon-apigateway-integration_ parameter etc.

Also Swagger Hub support AWS type of Swagger Configuration: https://swagger.io/blog/aws-getting-some-swagger-the-new-aws-api-gateway/

**Comment by semonte** [comment]
Thanks for creating an issue.

That would be a nice feature indeed. If there is demand for this, it should be implemented. But for now, there are other features in the backlog that take priority. @MaxVinogradov would you like to contribute to this feature? :)

**Comment by semonte** [comment]
Closing, this will likely never be implemented in the plugin.

**Comment by mattzuba** [comment]
Would you still accept a PR for this @semonte?

**Comment by semonte** [comment]
Yes I definitely would 👍
