### ISSUE TITLE
Doesn't detect openapi: 3.0.0 file

### ISSUE THREAD

**Issue by ari** [zalando/intellij-swagger#146]
If the file is not called swagger.yml (because we have several swagger schemas in the project), then this plugin doesn't detect the file as being a swagger file when it starts with:

`openapi: 3.0.0`

**Comment by ari** [comment]
I notice now that this looks like a duplicate of #131 however it is still a problem for me with Intellij Ultimate 2017.3 and 1.0.8 of this plugin.

Renaming the file to swagger.yaml didn't help. And 'swagger: 3.0.0' in the header causes the file to be detected as a swagger 2.0 version (going by the validation errors it found).

**Comment by semonte** [comment]
Thanks for reporting an issue. 

Can you be more specific, what doesn't work (autocompletion, reference, validation, etc.)?

**Comment by ari** [comment]
Since this is my first time using the plugin, I wasn't sure what it was supposed to do. There is no obvious UI that it has attached itself to a file. In my case, I was looking for validation errors. Even when I changed the file to clearly wrong swagger, there was no error.

Changing the first line to 'swagger: 2.0' give me errors I was expecting to see.

**Comment by semonte** [comment]
The Open API 3 validation is still non-existent. You should be able to navigate and refactor references, see autocompletion options and browser icons at the top right corner (it opens Swagger UI).

![image](https://user-images.githubusercontent.com/1151536/36659275-35f01c58-1ad4-11e8-9cba-74e97055f86f.png)

I will continue to add more features to Open API 3.

**Comment by ari** [comment]
Oh, I was confused by #108 I thought that meant the 3.0 libraries were already added for validation. I'll close this task then.

Its hard to tell because this plugin has no readme and no configuration and no UI, so it operates completely silently in the background. Which is nice when it works, but a bit hard to see what it is doing.
