### ISSUE TITLE
Which IntelliJ versions are compatible with this plugin?

### ISSUE THREAD

**Issue by keilw** [zalando/intellij-swagger#154]
I installed this plugin from the IntelliJ plugin repository and it also shows as being installed but it won't be used when I edit a Swagger YAML file. Is there any activation or is it only compatible with certain versions of IntelliJ?

Thanks.

**Comment by keilw** [comment]
Looks like it's working after all, the breadcrumbs shown in the screenshot are not the default (bottom) after the plugin is installed.

**Comment by semonte** [comment]
@keilw Good to hear this was not an issue after all.
