### ISSUE TITLE
Autocomplete/$refs doesn't work for yaml splitted into files

### ISSUE THREAD

**Issue by aprokopenko** [zalando/intellij-swagger#155]
Hi, 

I want to organize the API docs into several files, because it's easier to manage them.

I have main file `swagger.yaml`. Then I want to separate routes and models into different files.

Let's start with models. If I do a simple ref:

```
components:
  schemas:
    User:
      $ref:"user.yaml"
```

And create `user.yaml` like this:
```
type:object
properties:
   ...
```

Then autocompletion doesn't work. Because it's missing `openapi:3.0` header. And there is no way to set this file to understand that I use openapi object. So I need to write such code:

```
openapi:3.0
components:
  schemas:
    User:
       type:object
       properties:
           ....
```

And in this case autocompletion inside `swagger.yaml` and ref are not working, because I use such syntax:

```
$ref: 'user.yaml#/components/schemas/User'
```

(It doesn't suggest me the structure from other file and ctrl+click/cmd+click doesn't goes to a registered schema)

**Comment by semonte** [comment]
@aprokopenko Thanks for reporting an issue.

This issue relates to https://github.com/zalando/intellij-swagger/issues/134. PR https://github.com/zalando/intellij-swagger/pull/156 fixes the issue that references do not work in referenced files.

**Comment by aprokopenko** [comment]
Does your PR's available on Jetbrains plugin repo at once? My Storm doesn't notify me about any updates.
Or is there a way to install a "nightly build"?

**Comment by semonte** [comment]
You can download the latest release at https://github.com/zalando/intellij-swagger/releases/tag/1.0.11  (`intellij-swagger.zip`). I'll add it to the JetBrains repo soon, it still needs to be approved manually though (JetBrains process).

**Comment by maarten00** [comment]
The autocomplete issue is still broken sadly. I can fix it by adding `swagger: 2.0` at the top, but this raises another issue because the file is now marked as invalid: 

![screen shot 2018-04-25 at 09 35 07](https://user-images.githubusercontent.com/1579711/39231938-f935e14c-486b-11e8-96bd-65bfcb5e1052.png)

**Comment by semonte** [comment]
> The autocomplete issue is still broken sadly. I can fix it by adding swagger: 2.0 at the top, but this raises another issue because the file is now marked as invalid:

Yes that is expected, the latest release fixes the references inside a referenced file. This issue remains open.

**Comment by semonte** [comment]
@maarten00 As I understand the auto completion does not work in a file that is referenced by another referenced file? Auto completion should still work if the file is directly referenced from the main spec, can you confirm?

**Comment by maarten00** [comment]
Not for me. My definitions in my main file are as follows;
```
definitions:
  DossierComment:
    $ref: ./definitions/DossierComment.yml
  User:
    $ref: ./definitions/User.yml
```
As you can see the files are in a sub-folder. Autocomplete only works in the main file.

**Comment by aprokopenko** [comment]
Hi @semonte ,

My main issue about references are works fine. Great thanks for a quick fix!

Issues from @maarten00 is not related to my main topic. So if you have another issue for that - you can close this one.

**Comment by maarten00** [comment]
Sorry, It hought you were also having issues with autocomplete, I had no intention of hijacking your issue. I've gone ahead and opened a new issue for autocomplete: #160.

**Comment by semonte** [comment]
@aprokopenko great, I'll close this then.
