### ISSUE TITLE
Plugin can be applied to spring boot application yaml definitions.

### ISSUE THREAD

**Issue by redmachine2** [zalando/intellij-swagger#161]
Because the plugin is checking for a root key of "swagger", a spring boot application.yml with a swagger root gets detected as a spec file. This causes an application.yml file to have a whole bunch of errors which are annoying.

Locally I was able to fix by requiring the filename to at least contain "swagger" or "spec" before it would be considered a swagger file, but I'm not sure that fits all use cases. I'd be willing to implement a feature like this if I can get input on how a feature like this should work.

Looking through other issues I found #85, but I don't know if that is desired either as the auto detection is nice.

**Comment by semonte** [comment]
@redmachine2 thanks for creating the issue.

> I'd be willing to implement a feature like this if I can get input on how a feature like this should work.

We could make the existing Swagger spec detection more specific. For example, check that the file contains a root key `swagger` with a value `2.0`. Similar implementation could be done for an Open API file. How does that sound?

**Comment by redmachine2** [comment]
@semonte  That works for me, I'll try and work on that this week.
