### ISSUE TITLE
Can't find the Swagger UI buttons

### ISSUE THREAD

**Issue by burliayeu** [zalando/intellij-swagger#164]
Hi,
I've updated to the latest version and now I can't find the Swagger UI buttons.
Version 1.0.5 works for me, but any newest version doesn't have these buttons in the top on the editor tab.
Were they moved somewhere? Where to find them?
Thanks.

*IDEA 2018.1.3 RC on Windows 10.

**Comment by semonte** [comment]
Do you mean these buttons: 
![image](https://user-images.githubusercontent.com/1151536/39741177-792ae958-52a1-11e8-839c-edd36e9d15d0.png)

They should still be there, can you share the spec file?

**Comment by burliayeu** [comment]
Nope, I talked about these
![s1](https://user-images.githubusercontent.com/12219746/39768947-60de41fe-52f3-11e8-80a6-bb7b2d0170f2.PNG)

**Comment by semonte** [comment]
Unfortunately the embedded UI had to be removed from the plugin, starting from version https://github.com/zalando/intellij-swagger/releases/tag/1.0.8. The YAML text editor did not work well with the UI and I was not able to find a fix for this.

**Comment by burliayeu** [comment]
Oh, okay. I'll use the browser mode (didn't know about this feature).
Thanks for the information and for this useful plugin!👍
