### ISSUE TITLE
Upgrading swagger-ui

### ISSUE THREAD

**Issue by ghost** [zalando/intellij-swagger#169]
Please upgrade swagger-ui to the latest version. There are some fixes in the latest version that I'm hitting in the bundled version. I have tried to just replace the bundled version in the plugin directory but then everything stopped working.

In the meantime before a new release could you give guidance how to upgrade the bundled version locally?

**Comment by semonte** [comment]
Thanks for creating an issue.

It is not trivial to manually upgrade the bundled version, as we insert custom code to the `index.html`. For the future, I will keep a closer look at Swagger UI releases and keep the plugin up-to-date in regards to that.

**Comment by semonte** [comment]
I released a new version of the plugin with the latest Swagger UI. It is still pending JetBrains' approval.

**Comment by artemgordinskiy** [comment]
@semonte Sorry for a potentially dumb question but how do I render the docs using Swagger UI in the editor? I'm not seeing the swagger button anywhere (also not when searching among the editor actions) and opening the browsers doesn't seem to work either – I just see an empty page with a 
header. Using PyCharm 2018.2 with the latest plugin version on MacOS.

**Comment by ghost** [comment]
Opening the browser link in the right top corner used to work for me, but I didn't try with the latest plugin version.
