### ISSUE TITLE
[JSON]: Completion for fields should add trailing comma when needed

### ISSUE THREAD

**Issue by borlander** [zalando/intellij-swagger#17]
Consider following completion: 

```
{
  "swagger": "2.0",
  "info": {
    "tit<caret>
    "description": "Move your app forward with the Uber API",
    "version": "1.0.0"
  }
...
```

Completion for the field "title" is already implemented, but it would be nice if, after accepting the suggested field the final state would be: 

```
{
  "swagger": "2.0",
  "info": {
    "title": "<caret>",
    "description": "Move your app forward with the Uber API",
    "version": "1.0.0"
  }
...
```

(note the added quotes, placement of cursor and added comma).

For YAML flow there is no additional required markup, so it seems to be JSON-specific enhancement

**Comment by semonte** [comment]
@borlander Version 0.0.5 supports this (it also appends arrays and objects after the autocompleted key). Can you verify that you it works for you with version 0.0.5?

Currently autocompletion does not add a comma add the end, that would be a nice addition!

**Comment by borlander** [comment]
@semonte Quoting and cursor placement indeed works in the most recent version, thank you. 
I have changed the subj to cover only the part which is not yet implemented

**Comment by viatra2** [comment]
Using the very similar code we can also add a leading comma when inserting the property after the currently-last one. But it is more exotic and questionable use case so not yet implemented.
