### ISSUE TITLE
Fields completion should not suggest already existing fields

### ISSUE THREAD

**Issue by viatra2** [zalando/intellij-swagger#18]
<img width="538" alt="screen shot 2016-05-25 at 18 35 11" src="https://cloud.githubusercontent.com/assets/4850347/15548181/82f94eba-22a7-11e6-981a-1c1560854b3a.png">

Fields `description`, `title` and `version` are already present for `info`, duplicating them creates semantic error, so they probably should be filtered from the suggestions.

**Comment by semonte** [comment]
@viatra2 Agreed, existing keys need to be filtered.
