### ISSUE TITLE
Multiple Files

### ISSUE THREAD

**Issue by MrThreepwood** [zalando/intellij-swagger#184]
How do I reference other files and actually use them? The editor seems to understand references to other file definitions, but when opened in the browser it does not, saying a Base URL needs to be specified. Obviously for development this isn't an option, I'm developing locally and each person working in the repo is going to be working in a different path. The example seems to show doing something like this, but also doesn't use a real base url, how does this work?

**Comment by semonte** [comment]
Hi,

Unfortunately it is difficult to implement file references in the Swagger UI using local files. In case you want to use display local files and references in Swagger UI (with all the features), I suggest using the following approach https://github.com/swagger-api/swagger-ui/issues/1110#issuecomment-155873088

I will take another look at this to see if there is a way to implement file references using local files.

**Comment by MrThreepwood** [comment]
Currently when viewing in browser from the plugin, it builds and index.html and opens it in the browser. Other similar things for doc building or Javascript editing open a simple webserver with socket, which also allows it to update the browser window when updates occur. If this was done instead, would it be possible to have the server provide the referenced files through different endpoints (localhost/ref). Or perhaps on creation of the index.html file include referenced files as definitions in the primary file?

Of course, those both sound like a lot of work to implement.

**Comment by semonte** [comment]
A server would be great to have. IntelliJ can also provide a server and allows to query for resources within the project. Maybe there is a way for this to work.

**Comment by javac0dr** [comment]
Have you considered an approach where you inline all of the external references as part of building index.html?  With this approach index.html would be self-contained.  I know there are some javascript projects which will resolve all external references.  I'm not sure if there are any Java projects that do this.

**Comment by semonte** [comment]
> Have you considered an approach where you inline all of the external references as part of building index.html? With this approach index.html would be self-contained.

Sorry for missing this comment. This work is currently in progress! :)
