### ISSUE TITLE
Blank screen on preview

### ISSUE THREAD

**Issue by oleynikandrey** [zalando/intellij-swagger#190]
The plugin can't render OpenAPI spec, I see blank screen and errors in console:

<img width="1792" alt="screenshot 2018-10-01 at 11 23 36" src="https://user-images.githubusercontent.com/1157958/46277831-150bc480-c56d-11e8-9ccf-dd7537c43caf.png">

The same spec correctly rendered on editor.swagger.io without any warnings. How could I troubleshoot it?

**Comment by semonte** [comment]
Hey @oleynikandrey 

It seems that the related javascript files are not loaded. Could it be some add-on that is blocking requests for `file` protocol? I would suggest trying another browser if possible.

**Comment by oleynikandrey** [comment]
@semonte, I've tried Google Chrome, Firefox and Safari without success.
I saw such behaviour several times but the reason was an error in spec file, except last time.
I wonder is there any way to validate spec file before preview and somehow debug rendering process?

**Comment by semonte** [comment]
@oleynikandrey I'll check if it is possible to provide an error message when the spec is not valid YAML/JSON.

**Comment by semonte** [comment]
Here is the PR for this https://github.com/zalando/intellij-swagger/pull/195

**Comment by semonte** [comment]
Release 1.0.18 is out, the new version will give you feedback when something goes wrong with the Swagger UI.

**Comment by oleynikandrey** [comment]
Great, thank you!
