### ISSUE TITLE
Resolve to a PSI element from Zally inspection

### ISSUE THREAD

**Issue by semonte** [zalando/intellij-swagger#192]
Zally provides a path to a key/value that caused the violation. We should use this path to link the Intellij error to a PSI element. This will improve the developer experience; a user can click the error/warning and the cursor is moved to the correct position.

**Comment by maxim-tschumak** [comment]
Please use the [`pointer` element](https://github.com/zalando/zally/blob/master/server/src/main/resources/api/zally-api.yaml#L395) to navigate to the causing node in the YAML/JSON. (background: the `paths` element will be deprecated eventually)

**Comment by semonte** [comment]
> Please use the pointer element to navigate to the causing node in the YAML/JSON. (background: the paths element will be deprecated eventually)

Ok, good to know!
