### ISSUE TITLE
[JSON] Adding new object into array (e.g of parameters) produces error

### ISSUE THREAD

**Issue by viatra2** [zalando/intellij-swagger#20]
See screencast, note additional curly-brace inserted. 
![swagger-adding-parameters](https://cloud.githubusercontent.com/assets/4850347/15588700/64a7615c-238f-11e6-9271-3e1fd127d443.gif)

**Comment by semonte** [comment]
I am not able to reproduce this. Are you still getting the buggy behaviour?

**Comment by viatra2** [comment]
Indeed, it is fixed now, probably by your insertHandler's refactoring

**Comment by semonte** [comment]
Thanks for verifying.
