### ISSUE TITLE
Make x-audience configurable (zalando extensions)

### ISSUE THREAD

**Issue by cognifloyd** [zalando/intellij-swagger#225]
I'm looking at using zalando extensions while developing APIs where I work.
The concept of using `x-audience` to define the audience for a given API is excellent. However, the list of valid audiences does not make sense where I work.
https://github.com/zalando/intellij-swagger/blob/3c72b38075ce0f32be7c9904f305cf91333873eb/examples/extensions-zalando/src/main/java/org/zalando/intellij/swagger/examples/extensions/zalando/value/completion/swagger/SwaggerValues.java#L11-L16

Could you make this configurable (possibly with an option that says "deviate from zalando spec")? Then I would add at least three audiences: internal, customer, and partner.

**Comment by semonte** [comment]
Hey @cognifloyd 

The _Swagger Plugin Zalando Extension_ was not designed to be configurable, it is an example of how one can extend the features of the _Swagger plugin_. In this case, you would be better off writing an extension plugin for the Swagger plugin.

**Comment by cognifloyd** [comment]
OK. I will copy this then and modify it to suite my needs. Thanks!
