### ISSUE TITLE
Auto completion does not work with JSON Schema contributor

### ISSUE THREAD

**Issue by semonte** [zalando/intellij-swagger#228]
Swagger completion contributors are in conflict with the JetBrains JSON Schema completion contributors. We need to disable Swagger and OpenAPI schemas, as suggested by JetBrains https://intellij-support.jetbrains.com/hc/en-us/community/posts/360002721620-YAML-completion-contributor-

**Comment by aihua** [comment]
How long will the issue be updated to JetBrains Plugin Marketplace? @semonte @valgog @rupert654 @hjacobs @radarsh

**Comment by semonte** [comment]
The fix is available for the latest version, [1.0.24](https://plugins.jetbrains.com/plugin/8347-swagger/update/58093). Note that it requires JetBrains 2018.3 and up.
