### ISSUE TITLE
Decimal point is not allowed for numerical properties

### ISSUE THREAD

**Issue by xehpuk** [zalando/intellij-swagger#233]
Broken since **v1.0.23**:

I'm trying to specify a `maximum` of e.g. 999.99:

![Type is not allowed. Expected: number.](https://user-images.githubusercontent.com/3484906/52644715-a0b03d00-2edf-11e9-885f-5c0da0ead8be.png)
>Type is not allowed. Expected: number.

If there are at least three properties with the same specification, the error changes:

![Missing required property '$ref'](https://user-images.githubusercontent.com/3484906/52645167-83c83980-2ee0-11e9-9f71-519c25d0a164.png)
>Missing required property '$ref'

This has worked in **v1.0.21**.

**Comment by semonte** [comment]
Thanks for reporting, looks like a bug in the JSON Schema validator.

**Comment by semonte** [comment]
This seems to be a bug in the JSON Schema validator provided by JetBrains, I will make an issue for them and get some feedback.

In the meantime you can:

1) prefix the float values with `!!float 999.99` or
2) disable the JSON Schema validation (Preferences -> Editor -> Inspections -> Swagger/OpenAPI Inspections)

**Comment by semonte** [comment]
An issue for JetBrains has been created at https://youtrack.jetbrains.com/issue/IDEA-207702

**Comment by semonte** [comment]
Version 2019 is out, and it fixes the issue, closing this.
