### ISSUE TITLE
Value should be one of: "body"

### ISSUE THREAD

**Issue by profiprog** [zalando/intellij-swagger#234]
I have updated Swagger plugin to version v1.0.24 and it starts displaying error:
`Value should be one of: "body"`, but according to [reference](https://swagger.io/docs/specification/describing-parameters/) use `in: query` is correct.
![screnrec](https://media.giphy.com/media/czLczMFHMlSIlOO4cZ/giphy.gif)
Autocorrection just remove the value.

**Comment by semonte** [comment]
Thanks for reporting. Just to double check, is the specification OpenAPI 3? In Swagger, a `schema` is not allowed in query parameters. This would explain the error message.

**Comment by profiprog** [comment]
No I still depend on Swagger 2 `swagger: '2.0'`

**Comment by semonte** [comment]
Ok, in that case `schema` should not be in a parameter of `in: query` and the error is valid. Instead of schema, the parameter object should be something like:

```yaml
- in: query
  name: key
  type: string
```

As documented at https://swagger.io/docs/specification/2-0/describing-parameters/#query-parameters

**Comment by profiprog** [comment]
Tank you, that is a solution. No swagger tool (which I used) detect this as an error. Better error message could helpful, but it works for me.
