### ISSUE TITLE
[YAML] Allow non-sibling completion without need to correct an indentation

### ISSUE THREAD

**Issue by viatra2** [zalando/intellij-swagger#24]
This is a generic feature for editing of the YAML document with known structure. 
Consider the following: 

```
swagger: "2.0"
info:
  title: Uber API
  version: "1.0.0"
  description: Move your app forward with the Uber API
  ho<caret>
```

Here user has just entered the last field of the `info` object, pressed enter and possibly now wants to get back to editing of the main object. 

However, in order to enter e.g the `host` field, user is forced to get to the correct indentation level first, and only then she will be able to type `ho<completion>`. 
It would be nice if the same would work without the need to correct an indentation. 

Things to consider: 
- the feature should probably be activated only for editing of the last existing field of the sub-object
- the feature should probably be activated only when some matching field name of the parent is started to be typed (so `ho` in the snippet is important, and the `host` completion would NOT be suggested if the last line were empty)

**Comment by semonte** [comment]
In my opinion this is not needed, and will probably not be implemented. Closing.
