### ISSUE TITLE
IntelliJ 2019 support

### ISSUE THREAD

**Issue by reitzmichnicht** [zalando/intellij-swagger#242]
The last 1.0.24 has other compatibility settings so the IntelliJ 2019 beta tries always to downgrade the plugin to version 1.0.22.

Please release a version that initially supports the 2019 beta

**Comment by semonte** [comment]
Hey @reitzmichnicht version 1.0.25 that was released yesterday https://plugins.jetbrains.com/plugin/8347-swagger/update/59375 supports 2019.* versions.

**Comment by reitzmichnicht** [comment]
Great thanks a lot
