### ISSUE TITLE
Swagger/OpenAPI Inspections not respecting user-provided severity levels

### ISSUE THREAD

**Issue by GaryGSC** [zalando/intellij-swagger#257]
Hopefully this is the correct place to file this issue. Apologies if it isn't.

As the title implies, WebStorm gives me the option of specifying severity levels for different inspections. Some of my swagger documents have a lot of inspection errors related to #256, so I wanted to reduce the visual noise.

It turns out that setting the severity level to `Weak Warning` doesn't actually do anything. Either I get `Error`-level severity or I can turn the inspection off.

<img width="718" alt="severity" src="https://user-images.githubusercontent.com/7625337/55441924-bb12a880-5569-11e9-87f7-4143dd4b431e.png">

Poking around, I suspect that the issue is related to ReferenceInspection.java line [55](https://github.com/zalando/intellij-swagger/blob/master/src/main/java/org/zalando/intellij/swagger/inspection/reference/ReferenceInspection.java#L55) and/or [59](https://github.com/zalando/intellij-swagger/blob/master/src/main/java/org/zalando/intellij/swagger/inspection/reference/ReferenceInspection.java#L59) using `ProblemHighlightType.GENERIC_ERROR` instead of [`ProblemHighlightType.GENERIC_ERROR_OR_WARNING`](https://github.com/JetBrains/intellij-community/blob/master/platform/analysis-api/src/com/intellij/codeInspection/ProblemHighlightType.java).

I'd submit a PR, but I don't really want to download a Java IDE just for this.

Thanks!

**Versions:**
WebStorm 2019.1 (build #WS-191.6183.63, from March 21, 2019)
Swagger plugin v1.0.25

**Comment by semonte** [comment]
Thanks for reporting, this will be fixed!
