### ISSUE TITLE
Disable missing properties error for referenced definitions yaml file

### ISSUE THREAD

**Issue by TwunTee** [zalando/intellij-swagger#259]
When I am creating an definition yaml file I am getting an error saying paths and info properties are missing. When I am creating a definition file which will be referenced, paths and info are not necessary

"""
User.yaml
--------------
type: object
properties:
  name:
    type: string

"""

Is there a possibility of disabling missing properties error.

**Comment by semonte** [comment]
Can you provide a complete example? I can't reproduce the issue by creating a `User.yaml` file:

![image](https://user-images.githubusercontent.com/1151536/57070669-d09dfe00-6ce0-11e9-8344-6446310ea698.png)

**Comment by TwunTee** [comment]
I added swagger version tag on top of the file, that was causing the issue. I added swagger version tag as the autocomplete sometimes wouldn't work on files that were referenced. Now i tested the referenced files work without the swagger version tag and the autocomplete works without any issue. That resolves the problem thanks!
