### ISSUE TITLE
Ref to JSON file from OAS 3 YAML file not resolved

### ISSUE THREAD

**Issue by john3300** [zalando/intellij-swagger#262]
Starting with an OAS 3.0 YAML file, if I try to make a remote file reference to a schema in a JSON file the ref cannot be resolved.  ~~This isn't a problem with Swagger 2.0 files.~~

Here's a simple example to show the issue:

test-base.yaml
```
openapi: 3.0.0
info:
  title: Test
  version: '1.0'
servers:
  - url: http://localhost
paths:
  /cat:
    get:
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: 'cat.yaml#/components/schemas/cat'
  /dog:
    get:
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: 'dog.json#/components/schemas/dog'
```

cat.yaml (Ref resolves properly here)
```
components:
  schemas:
    cat:
      type: object
      properties:
        meow:
          type: string
```

dog.json (Ref fails to resolve here)
```
{
  "components": {
    "schemas": {
      "dog": {
        "type": "object",
        "properties": {
          "woof": {
            "type": "string"
          }
        }
      }
    }
  }
}
```

And here's a screenshot of the error:
![Screenshot at 2019-04-17 13-46-22](https://user-images.githubusercontent.com/10662490/56313395-220e9080-6118-11e9-9682-be5f55883ac0.png)

**Comment by john3300** [comment]
Actually, I've just discovered that this is problem with Swagger 2.0 files as well.  So it's not just an OAS 3.0 thing.

**Comment by semonte** [comment]
Thanks for reporting, this needs a fix indeed.

**Comment by Monkleys** [comment]
This seems to relate to this issue I opened [here](https://github.com/OAI/OpenAPI-Specification/issues/1927)
