### ISSUE TITLE
Permanent 100% CPU utilization through the swagger plugin.

### ISSUE THREAD

**Issue by axute** [zalando/intellij-swagger#263]
The CPU utilization by swagger is permanently at 100%, more precisely at the plugin itself 25% -30% and, hanging together, also the JIT compiler at 60% +.

This is very bad for a laptop, you can watch the battery while unloading.

**Comment by semonte** [comment]
Thanks for reporting, this needs to be looked at. There has not been much focus in evaluating the performance impact of introduced features.

**Comment by kevinrambaud** [comment]
Hey, this plugin is great! Well done. I have the same high CPU usage issue with a 2k lines swagger.

**Comment by vsaar** [comment]
What's the status of this issue? I'm experiencing the same and editing a file with 2k+ lines is really annoying.

**Comment by semonte** [comment]
I had a quick look today at this issue. There certainly are optimisations that can be done for the plugin. However, I also noticed a high CPU usage (100%) when editing an YAML file with 2k lines without the plugin installed.

Can you confirm my finding?

**Comment by kevinrambaud** [comment]
I observe some spikes in term of CPU usage when editing yaml file without this plugin but this is not constant, it quickly goes stops.

**Comment by NathanHazout** [comment]
My CPU usage goes up to 600%, and I have an i7 with 16GB RAM.
My file is also about 2k lines. There are validation errors so it could be related.

Without the plugin, as kevin says, it goes to 100% for a couple of seconds.

**Comment by vsaar** [comment]
I'm using JSON format, not YAML, so it's unlikely to be related to that. Also, when I deactivate the plugin, I don't experience any issues.

**Comment by austin1howard** [comment]
I'm also seeing this problem:
- 1000% CPU
- Macbook Pro 2018 (i7-8850H)
- 326 line yaml OpenAPI v3 file
- Pycharm 2019.1.3

Is there anything I can do to help diagnose? Logs, debugging? Really like this plugin but I have to disable it to make my machine usable at the moment.

**Comment by semonte** [comment]
[intellij-swagger.zip](https://github.com/zalando/intellij-swagger/files/3414494/intellij-swagger.zip)

Can you try the uploaded version to check does it solve the CPU and RAM issue? It contains a performance improvement for resolving references.

**Comment by austin1howard** [comment]
@semonte wonderful! No more high CPU usage for me. I had several references as well as &id001 type reference so I'm guessing that was the problem?

**Comment by seseloos** [comment]
@semonte solved the high CPU usage for me as well.

**Comment by retoo** [comment]
@semonte your branch improves the problem significantly  - thank you! Please merge :) 

**Note to others:** 
git clone https://github.com/zalando/intellij-swagger.git
git checkout issue-263
./gradlew build
Open Intellij point 'Install Plugin from Disk'  to 'build/distributions/intellij-swagger.zip'

**Comment by semonte** [comment]
Good to hear. Someone from the @zalando/team-intellij-swagger team needs to approve the PR https://github.com/zalando/intellij-swagger/pull/281 before merging

**Comment by NathanHazout** [comment]
Is this already in the marketplace?
Mine says 1.0.27 and still seems to go crazy

**Comment by kevinrambaud** [comment]
@nasht00 I don't think so, looks like the last version is 1.0.27 which is from May (https://plugins.jetbrains.com/plugin/8347-swagger/versions), they need to publish it on the marketplace.

**Comment by semonte** [comment]
Hey!

I have released a new version (1.0.28) to the marketplace, it should be available in a day or two. I am sorry for taking such a long time to update the plugin, many users are probably suffering from the CPU issue.
