### ISSUE TITLE
2 swagger.yaml with $ref and autocomplete

### ISSUE THREAD

**Issue by itairaz1** [zalando/intellij-swagger#269]
I have in my project 2 swagger.yaml (in different directories) that includes $ref to different files.
The files that has ref in first swagger.yaml are identify as swagger files and have autocomplete.
But the files that has ref in the second swagger.yaml doesn't identify as swagger and have yaml icon, without having autocomplete.

**Comment by semonte** [comment]
Thanks for reporting the issue, I am able to reproduce this.
