### ISSUE TITLE
Can't use tag_yaml

### ISSUE THREAD

**Issue by Monkleys** [zalando/intellij-swagger#270]
This is a weird one, but if I use `tag_yaml` for schema name, no reference will resolve to it. If I change it to any other name, it works. Is this a keyword in the plugin?

**Comment by semonte** [comment]
Seems like a bug in the regex at https://github.com/zalando/intellij-swagger/blob/master/src/main/java/org/zalando/intellij/swagger/reference/YamlReferenceContributor.java#L20. We need to escape the dot!
