### ISSUE TITLE
Plugin stopped working

### ISSUE THREAD

**Issue by psyhatter** [zalando/intellij-swagger#311]
I don’t know what to associate the problem with yet. The only thing that comes to mind is that I updated golang to version 1.14.4.
[stacktrace.txt](https://github.com/zalando/intellij-swagger/files/4730330/stacktrace.txt)

**Comment by psyhatter** [comment]
It seems to figure out what caused it.
I am trying to use models from another swagger file in a relative path, like this:
$ref: '../../../../api/swagger.yaml#/definitions/GenericError'

**Comment by tkrop** [comment]
Was fixed.
