### ISSUE TITLE
Plug-in not loading in IntelliJ CE 2020.3 for MacOS

### ISSUE THREAD

**Issue by Cactuspat2** [zalando/intellij-swagger#320]
Hi There. 

I recently upgraded my Mac and installed the latest version of IntelliJ. When I load the Swagger extension it loads, but after the IDE restarts it says 'Requires plugin 'org.zalando.intellij.swagger' to be installed. 

Here is the information from the 'about IntelliJ' panel
IntelliJ IDEA 2020.3.2 (Community Edition)
Build #IC-203.7148.57, built on January 25, 2021
Runtime version: 11.0.9.1+11-b1145.77 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Non-Bundled Plugins: IdeaVIM, AWSCloudFormation, aws.toolkit, com.amazon.ijbp

**Comment by tkrop** [comment]
Thanks for reporting. Can you please try out [beta 1.1](https://plugins.jetbrains.com/plugin/8347-swagger/versions/beta/117026) to see whether it fixes your issue?

**Comment by tkrop** [comment]
Please also have a look at #318.

**Comment by Cactuspat2** [comment]
The beta 1.1 fixed it. Thank you very much!!

**Comment by marcelstoer** [comment]
> The beta 1.1 fixed it.

Close this issue then?

**Comment by sanjP10** [comment]
Hi @tkrop 
After installing [beta 1.1](https://plugins.jetbrains.com/plugin/8347-swagger/versions/beta/117026)
I still have an issue when trying to click the button to open the swagger UI in a browser it does nothing.

I am also on a Mac and running 
IntelliJ 2021.1 Ultimate edition

Your plugin is super useful and would love for this to be functional again for my install.

**Comment by sambaranhazra** [comment]
Hi @sanjP10,

Can you please try with the version [1.1.1](https://plugins.jetbrains.com/plugin/8347-swagger/versions/beta/126353) from beta channel?

**Comment by sanjP10** [comment]
That worked

**Comment by sambaranhazra** [comment]
Hi @sanjP10 
Thanks for the feedback, we will soon release it to stable channel.
