### ISSUE TITLE
conflict with Rust plugin of JetBrains

### ISSUE THREAD

**Issue by zxeoc** [zalando/intellij-swagger#322]
When active Rust plugin from JetBrains and this at the same time, and set highlighting level to "All problems", it will stuck at "Analyzing(performing code analysis)" and prevent the editor from highlighting the Rust code.

**Comment by tkrop** [comment]
Thanks for reporting. Can you please try out [beta 1.1](https://plugins.jetbrains.com/plugin/8347-swagger/versions/beta/117026) and see whether it fixes the problem?

**Comment by tkrop** [comment]
Please also have a look at #318.

**Comment by zxeoc** [comment]
After installing the 1.1 beta, the issue solved. Thanks.
