### ISSUE TITLE
IntelliJ Inspections not working after upgrading IntelliJ IDEA to 2021.1

### ISSUE THREAD

**Issue by mojorero** [zalando/intellij-swagger#325]
Today I updated IntelliJ IDEA to the version 2021.1.

After that, the editor inspections did not work anymore (at least with Gradle and Maven projects with Java code). The inspections seen in the project explorer did work though.

Deinstalling the Plugin for Swagger helps. I was not able to find a better solution which allows me to keep using the Swagger Plugin.

After reinstalling the plugin again, I get this error:

![image](https://user-images.githubusercontent.com/11564614/115093181-cc913800-9f19-11eb-9508-f106240e7d01.png)

Here is the information from the 'about IntelliJ' panel

IntelliJ IDEA 2021.1 (Ultimate Edition)
Build #IU-211.6693.111, built on April 6, 2021
Runtime version: 11.0.10+9-b1341.35 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 4933M
Cores: 8
Non-Bundled Plugins: com.jetbrains.ChooseRuntime (1.2), org.sonarlint.idea (4.14.2.28348), aws.toolkit (1.26-211), org.jetbrains.kotlin (211-1.4.32-release-IJ6693.72), com.intellij.selenium (211.6693.108)
Kotlin: 211-1.4.32-release-IJ6693.72

**Comment by mojorero** [comment]
It is possible that the root cause for this problem is analyzed in this ticket https://github.com/zalando/intellij-swagger/issues/318
There is also a possible related PR https://github.com/zalando/intellij-swagger/pull/324

**Comment by marcelstoer** [comment]
Should be closed as a duplicate of #318.

**Comment by mojorero** [comment]
@marcelstoer thanks for your comment. I closed the ticket, as you suggested.
I also added the information to the mentioned ticket, as it is relevant to know that the IntelliJ editor validation is not working anymore.
