### ISSUE TITLE
Is this Plugin still being supported?

### ISSUE THREAD

**Issue by JohnVonNeumann** [zalando/intellij-swagger#330]
Hey there, I've run into a few issues with the plugin throwing errors on valid expressions in my swagger yaml definition, I was going to leave some issues but it seems to me like this project might be dead given there are multiple valid PRs open, accepted but not merged. If it's still alive, I'll post my issues, otherwise, what's the point?

Cheers, appreciate the work.

**Comment by sambaranhazra** [comment]
Hi @JohnVonNeumann ,

Thanks for asking, can you please share the issue you are facing and the respective IDE and plugin version you are using? Regarding the opened PR, we will soon close the PR for the deprecated Api soon, we have released that in beta channel and would do a verification before releasing to stable and merging.

Regards
Sambaran

**Comment by JohnVonNeumann** [comment]
Hey mate

Cheers for the quick reply, I've since found a fix for the main problem I was having, I guess largely my question is around the OpenAPI version 3 support, but I'm fairly new to OpenAPI so I'm probably just being a scrub. The other issues I had, I've forgotten about and it looks like I'm not facing them now. Sorry for the fuck around. Cheers for your work on this plugin.
