### ISSUE TITLE
Slightly strange operation of the plug-in

### ISSUE THREAD

**Issue by gskoczylas** [zalando/intellij-swagger#334]
Among other things, I have these plug-ins installed in IntelliJ:
•	Swagger
•	OpenAPI Specifications

A colleague has the same plug-ins installed. If a colleague opens Swagger's YAML file, he has web browser icons in the top right corner. He can click them and see his API in the browser of his choice.

I don't have these web browser icons. What could be causing me to not have these icons? Should I install or configure something else in IntelliJ?

**Comment by tkrop** [comment]
Sorry, we are missing the capacity to investigate this issue at the moment. If you find the problem and can deliver a solution we would be glad to merge it.
