### ISSUE TITLE
Definition not found. Invalid key.

### ISSUE THREAD

**Issue by curd0** [zalando/intellij-swagger#37]
Version 0.0.9 introduced following bugs/regressions in NodeJS projects:
1. Response references in swagger.yaml are not resolved. Reported error: _"Definition not found. Invalid key"_
2. All properties in "package.json" are highlighted red and reported as _"Invalid key"_ errors.

All errors are gone if Swagger plugin is disabled.

![swagger-yaml-error1](https://cloud.githubusercontent.com/assets/12750951/16045563/03b66118-3217-11e6-971e-1d5f0aaf84d9.png)
![swagger-yaml-error2](https://cloud.githubusercontent.com/assets/12750951/16045564/03b70dca-3217-11e6-89a7-1a9fdc614db2.png)
![swagger-yaml-error3](https://cloud.githubusercontent.com/assets/12750951/16045565/03d44232-3217-11e6-93d0-3bf12aec5721.png)

![package-json-errors](https://cloud.githubusercontent.com/assets/12750951/16045420/45f2351c-3216-11e6-9e4d-b42305d02411.png)

**Comment by semonte** [comment]
Thanks for the report, I have removed the plugin version from JetBrains and fix the issue.

**Comment by semonte** [comment]
Version 0.0.10 fixes the issue, I have published it.
