### ISSUE TITLE
URL double encoding in Chrome

### ISSUE THREAD

**Issue by jjhost** [zalando/intellij-swagger#394]
Click on open in chrome leads to "Site can't be reached" screen:
![image](https://github.com/zalando/intellij-swagger/assets/12336355/909d73e6-49ac-48c9-99cd-c63d6b9d7798)

**Comment by asaarilahti** [comment]
Thanks for reporting @jjhost! I'm not able to reproduce it (tried both "Open with" from menu and with the icons in the corner of the spec window). So would you be able to provide some more info?
- Version of the plugin
- IDEA version
- OS and OS version
- What are the exact steps you do to open it in Chrome?
- (Does the issue occur with other browsers?)
 
**edit**: Looking at the path, the OS seems to be Windows, so this likely occurs only under Windows.

**Comment by jjhost** [comment]
Hey there
Version of the plugin: 1.3.0
IDEA version: IntelliJ IDEA 2023.2.3 (Ultimate Edition), Build #IU-232.10072.27, built on October 11, 2023
OS and OS version:
Edition	Windows 10 Enterprise
Version	22H2
Installed on	‎24. ‎2. ‎2022
OS build	19045.3448
Experience	Windows Feature Experience Pack 1000.19044.1000.0


What are the exact steps you do to open it in Chrome?
click here:
(Does the issue occur with other browsers?)

**Comment by jjhost** [comment]
sorry, crtl+Enter sends things ..
I click here to open:
![image](https://github.com/zalando/intellij-swagger/assets/12336355/2457d6a2-0ea9-4d05-8297-ab779f4d5878)
other browsers: edge has same behavior as chrome, mozilla seems to de-double-encode the URL but displays nothing

When I un-double encode the URL, the content is correctly rendered ..

**Comment by ismail-bertalfilali** [comment]
Same problem for me as well.
Any  solutions please ?

**Comment by jsonstethem** [comment]
Same problem with all browsers

**Comment by zangailcs** [comment]
Same problem, downgrade to 1.2.0 can temporarily avoid this problem on my computer:
Win11+ IDEA2023.2.4 (Ultimate Edition) + Chrome + Plugin 1.2.0
