### ISSUE TITLE
Swagger Plugin incompatible with build 162.1121

### ISSUE THREAD

**Issue by TheTaylorHicks** [zalando/intellij-swagger#45]
Swagger Plugin is incompatible with Intellij IDEA 2016.2 (build 162.1121).

**Comment by semonte** [comment]
Hi @TheTaylorHicks and thanks for the report.

I am not able to reproduce the issue:

![image](https://cloud.githubusercontent.com/assets/1151536/16829284/74dfd9f4-4997-11e6-91dd-2fdded807e9f.png)

I do not know what version of Swagger Plugin you are using, but 0.0.16 should be compatible with IntelliJ IDEA 2016.2 (162.1121)

**Comment by TheTaylorHicks** [comment]
Sorry, I raised this issue due to a warning given by Intellij IDEA 2016.1 when prompted to upgrade, which turned out to be a false positive. After upgrading, Swagger Plugin works fine.

Apologies for any inconvenience caused.

**Comment by semonte** [comment]
No problem, good that you got everything working.
