### ISSUE TITLE
Plugin not available for PHPStorm 10.0.4

### ISSUE THREAD

**Issue by novas1r1** [zalando/intellij-swagger#46]
Hey,

I tried to install your swagger plugin via the PHPStorm plugin repository but there's only version 0.0.1 available (which doesn't work. It's always grayed out after installing it):

![image](https://cloud.githubusercontent.com/assets/2575205/17100898/a3a03f8a-5271-11e6-92b8-4464caf7088c.png)

So I downloaded the zip file with ne newest version (0.0.17) and tried to install it manually. But now it tells me: 

![image](https://cloud.githubusercontent.com/assets/2575205/17100917/c847de2e-5271-11e6-8961-45cccb1011f1.png)

What can I do to get it working?
Regards,
Verry

**Comment by semonte** [comment]
Hi,

Sorry for delayed reply. Unfortunately versions above 0.0.1 require newer versions of IDE, is it possible for you to upgrade to 2016.2? 0.0.1 has very limited features and is not actively maintained. With 2016.2 you can use the latest version:

![image](https://cloud.githubusercontent.com/assets/1151536/17506142/c7557f80-5e06-11e6-8fec-653bec953fdd.png)

**Comment by novas1r1** [comment]
Works now, thanks a lot =)! PHPStorm never told me that there's a new version available... :/

**Comment by semonte** [comment]
Great, I will close this issue then!
