### ISSUE TITLE
external JSON schema files not working -> update to newest Swagger-UI

### ISSUE THREAD

**Issue by dseichter** [zalando/intellij-swagger#47]
I am using external JSON schema files (v3/v4 compliant) and also using your Swagger Plugin in PyCharm.
I found out, that the Swagger-UI provided by your plugin, does not work correctly with external json files.
E.g. the following response:

```
      responses:
        200:
          description: laboratory results
          schema:
            $ref: 'http://localhost/lab-result-1014.json'
```

Your plugin (and the integrated swagger-ui) returns nothing:
![model schema](https://cloud.githubusercontent.com/assets/1712640/17139543/3d30dfbe-5345-11e6-91a6-34f8c3ff9f0a.png)

The newest swagger-ui returns the correct schema:
![model schema pass](https://cloud.githubusercontent.com/assets/1712640/17139577/66462bfc-5345-11e6-9358-2251c3bc23b9.png)

Thanks a lot!

**Comment by semonte** [comment]
Hi,

External file support does not exist at the moment. See also https://github.com/zalando/intellij-swagger/issues/41. For now, the UI does not work for this case.

**Comment by dseichter** [comment]
Good evening,
sorry for the long delay.
We are providing our json-schema files on our development machines by using a local webserver. So we can use e.g. $ref: 'http://localhost/lab-result-1014.json' to embed an external json schema. In production , we also provide that schema using a webservice.
The problem I meant was, that the swagger-plugin provides the swagger-ui version 2.1.4.
WIth this release, the external json schema is not shown in the swagger-ui.
Since swagger-ui v2.1.5 this issue is fixed. 

I just forked and updated swagger-ui to 2.2.0 (the index.html also includes your variable swaggerSpecification). The only problem I currently have, that I am not firm with Java to test the plugin by rebuilding it.

**Comment by dseichter** [comment]
I will close this issue. The **workaround** is to update the swagger-ui files manually (in the plugins directory), as long as the old swagger-ui version is shipped.

**Comment by lasomethingsomething** [comment]
Thanks for your interest in the project, @dseichter. Please reach out with any additional feedback or updates. :)
