### ISSUE TITLE
resolve splited swagger file and autocomplete

### ISSUE THREAD

**Issue by qfrank** [zalando/intellij-swagger#48]
A blog article about ["How to split a Swagger spec into smaller files"](http://azimi.me/2015/07/16/split-swagger-into-smaller-files.html)
1.It would be better if this plugin can resolve splited swagger files!Resolve means for $ref a relative path yaml,then we can click it like a hyperlink and jump to the target yaml file!
2.Also,when i edit User.yaml file which is mentioned in above article,autocomplete feature does not work...It would be good if autocomplete feature work in this situation!

**Comment by gjgarryuan** [comment]
@semonte Is there any plan of supporting splited swagger file?

**Comment by semonte** [comment]
Yes, navigating to files via $ref value is a high priority feature that the plugin needs to support. Also auto completion will be added to the referenced files.

**Comment by lasomethingsomething** [comment]
@garrychnca Hi Garry, thanks for your interest. Is this enhancement something you'd like to work on/contribute?

**Comment by semonte** [comment]
I have created two issues from this issue. #51 is well on its way. For #52 any help would be appreciated!
