### ISSUE TITLE
swagger-php annonation

### ISSUE THREAD

**Issue by barrystaes** [zalando/intellij-swagger#50]
We use https://github.com/zircote/swagger-php and have annonation in our PHP files (prefixed to the implementing function), much like phpdoc. We find it very useful to document our fast evolving JSON REST API. 

But right now this syntax in PhpStorm is just grey blob of text, so not very practical at all. Some code styling to help prevent syntax errors or typos. For me in particular quick navigation to definitions would be of use.

Is it feasable for the plugin to support these PHP annonations ?

Or might this be easyer to integrate in new, or other existing plugin like https://github.com/Haehnchen/idea-php-annotation-plugin (phpdoc) ?

**Comment by semonte** [comment]
Hi @barrystaes 

"intellij-swagger" is only a swagger specification editor and I think this kind of integration does not belong to the plugin. "phpdoc" is a better fit, but I would also consider a completely new plugin (e.g. intellij-swagger-php) as "phpdoc" and "intellij-swagger" are not perfect fits for this need.

**Comment by barrystaes** [comment]
Ok thanks for your insights!

Note to future self: brush up on Java and dive into https://confluence.jetbrains.com/display/PhpStorm/Plugin+Development
