### ISSUE TITLE
Compile error when trying to build via gradlew.bat runIdea

### ISSUE THREAD

**Issue by gjgarryuan** [zalando/intellij-swagger#54]
When I was trying to build the plugin by `gradlew.bat runIdea`, I ran into a compile error complaining:

```
E:\repos\intellij-swagger>gradlew.bat runIdea
:compileJava
E:\repos\intellij-swagger\src\main\java\org\zalando\intellij\swagger\ui\SwaggerUiUrlProvider.java:45: error: getUrl(OpenInBrowserRequest,VirtualFile) in SwaggerUiUrlProvider cannot override getUrl(OpenInBrowserRequest,VirtualFile) in BuiltInWebBrowserUrlProvider
    protected Url getUrl(@NotNull OpenInBrowserRequest request, @NotNull VirtualFile file) throws BrowserException {
                  ^
  overridden method does not throw BrowserException
1 error
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.721 secs

E:\repos\intellij-swagger>
```

I tried cleaning the temp dir for any gradle downloads as well as the .gradle dir under user folder, but same result.

Also, when I opened the source code and tried to go to the definition of the accused BuiltInWebBrowserUrlProvider, it opened a file called **BuiltInWebBrowserUrlProvider.kt** from C:\Users\gjyuan\.gradle\caches\modules-2\files-2.1\com.jetbrains.intellij.idea\ideaIC\LATEST-EAP-SNAPSHOT\94051ecd254e3276ca2ee955f8f888465e7724ee\ideaIC-LATEST-EAP-SNAPSHOT-sources.jar

The definition points to a kotlin file, is this expected?

**Comment by semonte** [comment]
Hi @garrychnca 

It seems that the LATEST-EAP-SNAPSHOT has some breaking changes for intellij-swagger plugin. I updated the build.gradle file to explicitly use version 2016.2. Please let me know if this works for you now.

**Comment by semonte** [comment]
And to answer to the last question: yes, kotlin files can be found here and there in intellij source code.

**Comment by gjgarryuan** [comment]
Yes, it compiles successfully if limited to 2016.2 version.

**Comment by semonte** [comment]
Great! I will close the issue then.
