### ISSUE TITLE
Unhandled exception while starting IntelliJ

### ISSUE THREAD

**Issue by nail2001** [zalando/intellij-swagger#58]
It did not happen before 0.20 (if I remember well) 

Every time I start IntelliJ I get this exception:

> To reindex this file IDEA has to be restarted: com.intellij.openapi.fileTypes.impl.AbstractFileType cannot be cast to com.intellij.openapi.fileTypes.LanguageFileType
> java.lang.ClassCastException: com.intellij.openapi.fileTypes.impl.AbstractFileType cannot be cast to com.intellij.openapi.fileTypes.LanguageFileType
>     at com.intellij.util.indexing.FileContentImpl.createFileFromText(FileContentImpl.java:97)
>     at com.intellij.util.indexing.FileContentImpl.getPsiFile(FileContentImpl.java:75)
>     at org.zalando.intellij.swagger.index.SwaggerDataIndexer.map(SwaggerDataIndexer.java:34)
>     at org.zalando.intellij.swagger.index.SwaggerDataIndexer.map(SwaggerDataIndexer.java:25)
>     at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:457)
>     at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1633)
>     at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$8(FileBasedIndexImpl.java:1559)
>     at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:505)
>     at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1516)
>     at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1501)
>     at com.intellij.util.indexing.UnindexedFilesUpdater.lambda$indexFiles$0(UnindexedFilesUpdater.java:107)
>     at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.lambda$run$0(CacheUpdateRunner.java:219)
>     at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1026)
>     at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.lambda$run$1(CacheUpdateRunner.java:236)
>     at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
>     at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
>     at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
>     at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
>     at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
>     at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:232)
>     at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
>     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>     at java.lang.Thread.run(Thread.java:745)

**Comment by semonte** [comment]
I will take a look at this. Are you able to share your project so that I could test this with your setup?

**Comment by nail2001** [comment]
I was unable to reproduce the error myself on a different computer. Therefore I made a clean install of intellij and the problem is gone now.

**Comment by semonte** [comment]
Ok, please let me know if the problem reappears. I have not heard of a similar issue before, so it does not make sense to invest time in this for now.
