### ISSUE TITLE
Autocomplete doesn't work in referenced operation files

### ISSUE THREAD

**Issue by kexsteve** [zalando/intellij-swagger#59]
swagger.yaml
<img width="390" alt="screen shot 2016-10-26 at 12 11 14 am" src="https://cloud.githubusercontent.com/assets/5917562/19713045/c1c687fc-9b10-11e6-9b92-d8a6ab14b414.png">

hospitals.yaml
<img width="341" alt="screen shot 2016-10-26 at 12 13 04 am" src="https://cloud.githubusercontent.com/assets/5917562/19713079/057f65cc-9b11-11e6-8d58-b4f2699dd358.png">

**Comment by semonte** [comment]
Auto completion for referenced files is implemented in https://github.com/zalando/intellij-swagger/pull/55. However, it only supports definition and parameter references as they are usually reused across the specification.

Obviously there is a need to support operation references as you pointed out :)
