### ISSUE TITLE
Swagger detection by different file names

### ISSUE THREAD

**Issue by semonte** [zalando/intellij-swagger#6]
From https://plugins.jetbrains.com/plugin/8347:

clint@computer.org wrote:

Would it make sense to support openapi.yml as the filename as well? I haven't seen any examples so I'm not sure if people are putting a dash in the name or not.

**Comment by ePaul** [comment]
In many projects I've seen quite different names for the YAML files, often derived from the name of the API.

I guess catching the "swagger" field name should be enough for all of them (even if that doesn't work from the very start).

**Comment by hjacobs** [comment]
Please use the recommended `.yaml` extension and not  `.yml`.

**Comment by semonte** [comment]
Currently Swagger file is detected if:
- its filename is swagger.json, swagger.yaml or swagger.yml or
- a "swagger" field exists

It would make sense to create a Swagger template for new files. Template would contain all required fields and everything would work right from the start. I created #33 for this.
