### ISSUE TITLE
Auto-Refresh for browser preview

### ISSUE THREAD

**Issue by lukx** [zalando/intellij-swagger#65]
I have found this plugin the most convenient way for me to edit swagger files (i prefer it over the swagger-editor, for example).
What I'd really love to see is an auto-refresh feature for the excellent browser preview - so that whenever I save, the page in the browser reloads or updates the relevant parts, similar to what the various markdown plugins do.

**Comment by semonte** [comment]
That is a good idea, care to contribute @Lukx? :)

**Comment by lukx** [comment]
Absolutely, I was planning to look into it on saturday

**Comment by semonte** [comment]
Great! Don't hesitate to ask if you have any questions regarding the code.

**Comment by SunMar** [comment]
@lukx how do you actually get a browser preview? I can't find it, probably overlooking something. I have in Tools > Web Browsers my browsers configured. Thank you!

**Comment by semonte** [comment]
@SunMar You can open the Swagger UI from the top right corner of the editor when you have a Swagger file opened:

![image](https://user-images.githubusercontent.com/1151536/29015122-0217ad0a-7b4d-11e7-8795-2665dd19f4ea.png)
