### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by grosch** [zalando/intellij-swagger#74]
I installed this plugin via inside PhpStorm and restarted, but I'm not seeing anything special happening with my yaml file.  Do I have to do something specific to get features?  Is there any documentation for this?

**Comment by semonte** [comment]
Hi @grosch. You don't need to do anything special to activate the plugin. Just open a Swagger specification file and the features (auto completion, navigation to references, etc.) will work. If you are still having problems you need to provide which version of PhpStorm and Swagger plugin you are using.
