### ISSUE TITLE
Warnings for unused definitions and parameters

### ISSUE THREAD

**Issue by carlansley** [zalando/intellij-swagger#78]
Not sure if this exists already and I'm missing how to turn it on, or a possible future enhancement, but would love to see unused definitions and parameters shown as warnings within the editor.  

Thanks for the great plugin!

**Comment by semonte** [comment]
This would be a nice feature indeed! I'll label it as an enhancement.

**Comment by semonte** [comment]
FYI: this is still planned to be implemented, although the issue is quite old.

**Comment by semonte** [comment]
It took a while, this will be available in the next published release https://github.com/zalando/intellij-swagger/releases/tag/1.0.12
