### ISSUE TITLE
Pluggin fails to load due to missing dependency. Pycharm CE

### ISSUE THREAD

**Issue by leroyshirto** [zalando/intellij-swagger#8]
Using:
PyCharm Community Edition 2016.1.3
Build #PC-145.971, built on May 3, 2016
JRE: 1.8.0_40-release-b132 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

The plugin fails to load due to a missing dependency on org.jetbrains.plugins.yaml

<img width="498" alt="screen shot 2016-05-15 at 21 58 50" src="https://cloud.githubusercontent.com/assets/6397141/15276713/2531760c-1ae8-11e6-8476-bad0b5aa3445.png">

**Comment by semonte** [comment]
Hi,

Thanks for the detailed report. I just discovered that YAML plugin is only available in PyCharm Ultimate edition. I have updated the plugin page (https://plugins.jetbrains.com/plugin/8347) regarding this.

There was also an issue with PyCharm Ultimate and RubyMine, version 0.0.3 fixes them. Issue is described in  commit de0f15fb447b6a8eb4cf7eecba72fdcea8636d0a
