### ISSUE TITLE
PHPStorm2017.1 don't work in annotates?

### ISSUE THREAD

**Issue by peterleng** [zalando/intellij-swagger#84]
PHPStorm2017.1 don't work in annotates?  I remmeber it can autocomplete in php annotates on old version phpstorms

**Comment by NabiKAZ** [comment]
Seem resolved this issue with latest update.
I checked on phpstorm 2017.1.3 and works well.
Thanks.

**Comment by semonte** [comment]
Closing, nothing to do.
