### ISSUE TITLE
Allow to mark a yaml file as swagger

### ISSUE THREAD

**Issue by PetrGlad** [zalando/intellij-swagger#85]
Allow to tell Idea that a particular yaml/yml file should be edited as swagger spec.
Currently if file name do not match predefined pattern it is not recognized as specification.

**Comment by semonte** [comment]
The plugin also recognizes a Swagger file if the file has a key named `swagger`. This feature would sure be nice to have, but not very high priority. @PetrGlad do you want to contribute :) ?

**Comment by semonte** [comment]
Closing, nothing to do.
