### ISSUE TITLE
YAML merge keys are identified as as Invalid Key errors

### ISSUE THREAD

**Issue by jamiethompson** [zalando/intellij-swagger#87]
When using YAML merge keys to merge in aliases, the merge keys are identified as errors 'Invalid key'

Example YAML

```yaml
responses:
  <<: *default_response
  201:
    description: Created
    schema:
      $ref: '#/definitions/ProductVariation'
```

**Comment by semonte** [comment]
Hi @jamiethompson 

Thanks for reporting this, needs to be fixed.

**Comment by jamiethompson** [comment]
No problem. I have also just this morning noticed that using merge keys also appears to break the Swagger UI generation.

**Comment by semonte** [comment]
@jamiethompson are you able to share the Swagger file a bit more? How does the `default_response` element look like? 

I want to create proper tests for the merge keys, this would be valuable test data.

**Comment by jamiethompson** [comment]
No problem, here's what the `&default_response` anchor looks like

```yaml
responses:
    Default: &default_response
      # Errors
      400:
        $ref: '#/responses/400BadRequest'
      401:
        $ref: '#/responses/401Unauthorized'
      403:
        $ref: '#/responses/403Forbidden'
      404:
        $ref: '#/responses/404NotFound'
      409:
        $ref: '#/responses/409Conflict'
      429:
        $ref: '#/responses/429TooManyRequests'
      500:
        $ref: '#/responses/500InternalServerError'
      503:
        $ref: '#/responses/503ServiceUnavailable'
```

Let me know if you need anything more

**Comment by semonte** [comment]
> No problem. I have also just this morning noticed that using merge keys also appears to break the Swagger UI generation.

Unfortunately Jackson does not support transforming YAML to JSON with merge keys and anchors (we use Jackson to transform YAML to JSON for Swagger UI).

**Comment by semonte** [comment]
Thanks for the example spec, this is fixed now. I still need to make a release, should happen by the end of next week.

**Comment by jamiethompson** [comment]
No problem. I look forward to the release 😄

**Comment by semonte** [comment]
FYI: I made a PR for JetBrains about anchors and aliases in YAML files. In the future we can hopefully jump to declaration by clicking an alias :) https://github.com/JetBrains/intellij-community/pull/577

**Comment by jamiethompson** [comment]
Wow, thanks. That would make writing large specs so much easier.

**Comment by semonte** [comment]
@jamiethompson The plugin has been updated, you should no longer see the errors.

**Comment by jamiethompson** [comment]
Thank you. Updated today. Works a treat.

**Comment by naufq** [comment]
> > No problem. I have also just this morning noticed that using merge keys also appears to break the Swagger UI generation.
> 
> Unfortunately Jackson does not support transforming YAML to JSON with merge keys and anchors (we use Jackson to transform YAML to JSON for Swagger UI).

Does Swagger UI still suffer from this issue?
