### ISSUE TITLE
Slashes in YAML anchors cause parsing errors

### ISSUE THREAD

**Issue by jamiethompson** [zalando/intellij-swagger#88]
Using slashes in YAML anchors appears to cause a parsing error:

```
YAML decoding problem: while scanning an anchor
 in 'reader', line 54, column 17:
        Pagination: &x-components/headers/Pagination
                    ^
expected alphabetic or numeric character, but found /(47)
 in 'reader', line 54, column 30:
        Pagination: &x-components/headers/Pagination
```

The YAML spec seems to suggest that these characters are acceptable

http://www.yaml.org/spec/1.2/spec.html#id2785586

> Anchor names must not contain the “[”, “]”, “{”, “}” and “,” characters. These characters would cause ambiguity with flow collection structures.

**Comment by semonte** [comment]
@jamiethompson I assume this error is shown when Swagger UI is used? We use Jackson (https://github.com/FasterXML/jackson) to convert YAML to JSON and it does not support anchors unfortunately.

**Comment by jamiethompson** [comment]
No, this is actually within the IDE. Those errors are taken from the "IDE Fatal Errors" dialog.

Regarding Swagger UI though, I do find that my YAML with anchors causes the Swagger UI to fail to generate, so thanks for the explanation why. Do you envisage any way around this in future?

**Comment by semonte** [comment]
intellij-swagger version 0.0.29 (latest version) should not print those errors. There is really no way around it, only to avoid anchors and merge keys if Swagger UI is used. 

I will keep an eye on Jackson to check if this will be supported in the future.

**Comment by jamiethompson** [comment]
Fair enough. Hopefully OpenAPI 3.0 will remove our need to use YAML anchors for keeping things DRY.
