### ISSUE TITLE
OpenAPI 3.0 (Swagger 3.0) support

### ISSUE THREAD

**Issue by garethmcc** [zalando/intellij-swagger#89]
Are there perhaps any plans to add support for the new spec being released soon?

**Comment by semonte** [comment]
Swagger 3.0 support is planned, and it will eventually be supported. It is high on the priority list, but it's quite a big feature to add.

OpenAPI 3 branch: https://github.com/zalando/intellij-swagger/tree/issue-89 Progress so far:

- [X] Field autocompletion
- [x] Value autocompletion
- [X] Local component references
- [ ] External component references
- [X] Swagger UI with OpenAPI 3

**Comment by semonte** [comment]
OpenAPI v3 is now officially released (https://swagger.io/announcing-openapi-3-0/). Specs can be found at https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md

**Comment by xenohunter** [comment]
@semonte hello! How soon its support will be added to the plugin?

**Comment by semonte** [comment]
OpenAPI 3.0 support is at the top of the backlog, no other features will be added until OpenAPI 3.0 support is finished. My estimate is that it will be available in couple of months.

**Comment by semonte** [comment]
Beta version is available at https://github.com/zalando/intellij-swagger/releases/tag/1.0.0-beta Please give it a try and create an issue if you encounter bugs!

**Comment by semonte** [comment]
Closing this, OpenAPI support was added by https://github.com/zalando/intellij-swagger/pull/103. The core support is there, now it is a matter of gradually adding more functionality when needs arise.
